mod aggregate_cells;
mod aggregate_column;
mod aggregate_header;
mod aggregate_rows;
mod aggregate_value;
mod all_cols;
mod build_join;
mod candidate;
mod cell;
mod check_one_column;
mod check_qualifier;
mod check_shape;
mod col;
mod col_header;
mod col_row;
mod col_value;
mod column_check;
mod column_rows;
mod combine;
mod compare_key;
mod compare_keys;
mod count_present;
mod directed;
mod distinct_headers;
mod dispatch_sum;
mod eval;
mod existing_columns;
mod find_joined;
mod has_column;
mod header_name;
mod header_table;
mod held_cells;
mod holder_label;
mod holder_rows;
mod holder_table;
mod is_id_of;
mod is_joined_ref;
mod item_columns;
mod join_columns;
mod join_holder;
mod join_plan;
mod join_refusal;
mod joined_candidates;
mod keep;
mod known_table;
mod linked;
mod matched_plan;
mod mixed_types;
mod named_cols;
mod not_number;
mod one_col;
mod one_type;
mod order;
mod orientation;
mod output_headers;
mod other_name;
mod overflow;
mod pair_candidates;
mod plan;
mod present_cell;
mod present_cells;
mod project;
mod projected_cols;
mod push_unique;
mod ref_col;
mod ref_table_name;
mod referenced_columns;
mod references;
mod relation_side;
mod resolve;
mod row_cells;
mod row_column;
mod same_id;
mod single_candidate;
mod source_row;
mod sum_column;
mod sum_decimals;
mod sum_integers;
mod table_cols;
mod target_table;
mod targets_id;
mod to_decimal;
mod to_integer;
mod unordered_aggregate;

use check_shape::check_shape;
use combine::combine;
use keep::keep;
use order::order;
use plan::plan;
use project::project;
use crate::query::Select;
use crate::refusal::QueryRefusal;
use crate::rows::Rows;

impl super::Base {
    pub fn select(&self, query: &Select) -> Result<Rows, QueryRefusal> {
        let resolved = plan(&self.tables, query)?;
        check_shape(&resolved, query)?;
        let candidates = combine(&resolved);
        let kept = keep(&resolved, candidates, query);
        let ordered = order(&resolved, kept, &query.order)?;
        project(&resolved, query, &ordered)
    }
}
